/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const StorageCondition = IDL.Variant({
  'roomTemperature' : IDL.Null,
  'refrigerated' : IDL.Null,
  'hotStorage' : IDL.Null,
});
export const DonationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'pickedUp' : IDL.Null,
  'rejected' : IDL.Null,
  'confirmed' : IDL.Null,
  'accepted' : IDL.Null,
});
export const FoodDonation = IDL.Record({
  'id' : IDL.Nat,
  'status' : DonationStatus,
  'latitude' : IDL.Float64,
  'city' : IDL.Text,
  'neighborhood' : IDL.Text,
  'donorName' : IDL.Text,
  'unit' : IDL.Text,
  'cookTime' : Time,
  'claimedBy' : IDL.Opt(IDL.Nat),
  'longitude' : IDL.Float64,
  'timestamp' : Time,
  'quantity' : IDL.Float64,
  'storageCondition' : StorageCondition,
  'foodType' : IDL.Text,
});
export const NGO = IDL.Record({
  'id' : IDL.Nat,
  'latitude' : IDL.Float64,
  'ratingCount' : IDL.Nat,
  'city' : IDL.Text,
  'neighborhood' : IDL.Text,
  'name' : IDL.Text,
  'longitude' : IDL.Float64,
  'rating' : IDL.Float64,
  'capacity' : IDL.Nat,
});
export const Volunteer = IDL.Record({
  'id' : IDL.Nat,
  'latitude' : IDL.Float64,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'availability' : IDL.Text,
  'longitude' : IDL.Float64,
  'rating' : IDL.Float64,
});
export const EntityType = IDL.Variant({
  'ngo' : IDL.Null,
  'admin' : IDL.Null,
  'hotel' : IDL.Null,
  'volunteer' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'city' : IDL.Text,
  'neighborhood' : IDL.Text,
  'name' : IDL.Text,
  'entityType' : EntityType,
});
export const ImpactCounters = IDL.Record({
  'totalMealsSaved' : IDL.Nat,
  'cityBreakdown' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'co2Reduced' : IDL.Float64,
  'totalPeopleFed' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelClaim' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'claimDonation' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'createFoodDonation' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        Time,
        StorageCondition,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
      ],
      [IDL.Nat],
      [],
    ),
  'getAllDonations' : IDL.Func([], [IDL.Vec(FoodDonation)], ['query']),
  'getAllNgosSortedByRating' : IDL.Func([], [IDL.Vec(NGO)], ['query']),
  'getAllVolunteersSortedByName' : IDL.Func(
      [],
      [IDL.Vec(Volunteer)],
      ['query'],
    ),
  'getAvailableDonationsForVolunteers' : IDL.Func(
      [],
      [IDL.Vec(FoodDonation)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFoodDonation' : IDL.Func([IDL.Nat], [IDL.Opt(FoodDonation)], ['query']),
  'getImpactCounters' : IDL.Func([], [ImpactCounters], ['query']),
  'getMyNgoRating' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Float64)], ['query']),
  'getNgoRatingSummary' : IDL.Func(
      [IDL.Nat],
      [IDL.Float64, IDL.Nat],
      ['query'],
    ),
  'getNgosByCity' : IDL.Func([IDL.Text], [IDL.Vec(NGO)], ['query']),
  'getPendingDonationsSortedByTimestamp' : IDL.Func(
      [],
      [IDL.Vec(FoodDonation)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProfilesByEntityType' : IDL.Func(
      [EntityType],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'getVolunteersByCity' : IDL.Func([IDL.Text], [IDL.Vec(Volunteer)], ['query']),
  'isAdminCaller' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rateNgo' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateFoodDonationStatus' : IDL.Func([IDL.Nat, DonationStatus], [], []),
  'updateImpactCounters' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Float64, IDL.Text, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const StorageCondition = IDL.Variant({
    'roomTemperature' : IDL.Null,
    'refrigerated' : IDL.Null,
    'hotStorage' : IDL.Null,
  });
  const DonationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'pickedUp' : IDL.Null,
    'rejected' : IDL.Null,
    'confirmed' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const FoodDonation = IDL.Record({
    'id' : IDL.Nat,
    'status' : DonationStatus,
    'latitude' : IDL.Float64,
    'city' : IDL.Text,
    'neighborhood' : IDL.Text,
    'donorName' : IDL.Text,
    'unit' : IDL.Text,
    'cookTime' : Time,
    'claimedBy' : IDL.Opt(IDL.Nat),
    'longitude' : IDL.Float64,
    'timestamp' : Time,
    'quantity' : IDL.Float64,
    'storageCondition' : StorageCondition,
    'foodType' : IDL.Text,
  });
  const NGO = IDL.Record({
    'id' : IDL.Nat,
    'latitude' : IDL.Float64,
    'ratingCount' : IDL.Nat,
    'city' : IDL.Text,
    'neighborhood' : IDL.Text,
    'name' : IDL.Text,
    'longitude' : IDL.Float64,
    'rating' : IDL.Float64,
    'capacity' : IDL.Nat,
  });
  const Volunteer = IDL.Record({
    'id' : IDL.Nat,
    'latitude' : IDL.Float64,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'availability' : IDL.Text,
    'longitude' : IDL.Float64,
    'rating' : IDL.Float64,
  });
  const EntityType = IDL.Variant({
    'ngo' : IDL.Null,
    'admin' : IDL.Null,
    'hotel' : IDL.Null,
    'volunteer' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'city' : IDL.Text,
    'neighborhood' : IDL.Text,
    'name' : IDL.Text,
    'entityType' : EntityType,
  });
  const ImpactCounters = IDL.Record({
    'totalMealsSaved' : IDL.Nat,
    'cityBreakdown' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'co2Reduced' : IDL.Float64,
    'totalPeopleFed' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelClaim' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'claimDonation' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'createFoodDonation' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          Time,
          StorageCondition,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
        ],
        [IDL.Nat],
        [],
      ),
    'getAllDonations' : IDL.Func([], [IDL.Vec(FoodDonation)], ['query']),
    'getAllNgosSortedByRating' : IDL.Func([], [IDL.Vec(NGO)], ['query']),
    'getAllVolunteersSortedByName' : IDL.Func(
        [],
        [IDL.Vec(Volunteer)],
        ['query'],
      ),
    'getAvailableDonationsForVolunteers' : IDL.Func(
        [],
        [IDL.Vec(FoodDonation)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFoodDonation' : IDL.Func([IDL.Nat], [IDL.Opt(FoodDonation)], ['query']),
    'getImpactCounters' : IDL.Func([], [ImpactCounters], ['query']),
    'getMyNgoRating' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Float64)], ['query']),
    'getNgoRatingSummary' : IDL.Func(
        [IDL.Nat],
        [IDL.Float64, IDL.Nat],
        ['query'],
      ),
    'getNgosByCity' : IDL.Func([IDL.Text], [IDL.Vec(NGO)], ['query']),
    'getPendingDonationsSortedByTimestamp' : IDL.Func(
        [],
        [IDL.Vec(FoodDonation)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProfilesByEntityType' : IDL.Func(
        [EntityType],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'getVolunteersByCity' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Volunteer)],
        ['query'],
      ),
    'isAdminCaller' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rateNgo' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateFoodDonationStatus' : IDL.Func([IDL.Nat, DonationStatus], [], []),
    'updateImpactCounters' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Float64, IDL.Text, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };