/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type DonationStatus = { 'pending' : null } |
  { 'pickedUp' : null } |
  { 'rejected' : null } |
  { 'confirmed' : null } |
  { 'accepted' : null };
export type EntityType = { 'ngo' : null } |
  { 'admin' : null } |
  { 'hotel' : null } |
  { 'volunteer' : null };
export interface FoodDonation {
  'id' : bigint,
  'status' : DonationStatus,
  'latitude' : number,
  'city' : string,
  'neighborhood' : string,
  'donorName' : string,
  'unit' : string,
  'cookTime' : Time,
  'claimedBy' : [] | [bigint],
  'longitude' : number,
  'timestamp' : Time,
  'quantity' : number,
  'storageCondition' : StorageCondition,
  'foodType' : string,
}
export interface ImpactCounters {
  'totalMealsSaved' : bigint,
  'cityBreakdown' : Array<[string, bigint]>,
  'co2Reduced' : number,
  'totalPeopleFed' : bigint,
}
export interface NGO {
  'id' : bigint,
  'latitude' : number,
  'ratingCount' : bigint,
  'city' : string,
  'neighborhood' : string,
  'name' : string,
  'longitude' : number,
  'rating' : number,
  'capacity' : bigint,
}
export type StorageCondition = { 'roomTemperature' : null } |
  { 'refrigerated' : null } |
  { 'hotStorage' : null };
export type Time = bigint;
export interface UserProfile {
  'city' : string,
  'neighborhood' : string,
  'name' : string,
  'entityType' : EntityType,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Volunteer {
  'id' : bigint,
  'latitude' : number,
  'city' : string,
  'name' : string,
  'availability' : string,
  'longitude' : number,
  'rating' : number,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelClaim' : ActorMethod<[bigint, bigint], undefined>,
  'claimDonation' : ActorMethod<[bigint, bigint], undefined>,
  'createFoodDonation' : ActorMethod<
    [
      string,
      string,
      number,
      string,
      Time,
      StorageCondition,
      string,
      string,
      number,
      number,
    ],
    bigint
  >,
  'getAllDonations' : ActorMethod<[], Array<FoodDonation>>,
  'getAllNgosSortedByRating' : ActorMethod<[], Array<NGO>>,
  'getAllVolunteersSortedByName' : ActorMethod<[], Array<Volunteer>>,
  'getAvailableDonationsForVolunteers' : ActorMethod<[], Array<FoodDonation>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFoodDonation' : ActorMethod<[bigint], [] | [FoodDonation]>,
  'getImpactCounters' : ActorMethod<[], ImpactCounters>,
  'getMyNgoRating' : ActorMethod<[bigint], [] | [number]>,
  'getNgoRatingSummary' : ActorMethod<[bigint], [number, bigint]>,
  'getNgosByCity' : ActorMethod<[string], Array<NGO>>,
  'getPendingDonationsSortedByTimestamp' : ActorMethod<[], Array<FoodDonation>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProfilesByEntityType' : ActorMethod<[EntityType], Array<UserProfile>>,
  'getVolunteersByCity' : ActorMethod<[string], Array<Volunteer>>,
  'isAdminCaller' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rateNgo' : ActorMethod<[bigint, number], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateFoodDonationStatus' : ActorMethod<[bigint, DonationStatus], undefined>,
  'updateImpactCounters' : ActorMethod<
    [bigint, bigint, number, string, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];