/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ImpactCounters {
    totalMealsSaved: bigint;
    cityBreakdown: Array<[string, bigint]>;
    co2Reduced: number;
    totalPeopleFed: bigint;
}
export interface FoodDonation {
    id: bigint;
    status: DonationStatus;
    latitude: number;
    city: string;
    neighborhood: string;
    donorName: string;
    unit: string;
    cookTime: Time;
    claimedBy?: bigint;
    longitude: number;
    timestamp: Time;
    quantity: number;
    storageCondition: StorageCondition;
    foodType: string;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Volunteer {
    id: bigint;
    latitude: number;
    city: string;
    name: string;
    availability: string;
    longitude: number;
    rating: number;
}
export interface NGO {
    id: bigint;
    latitude: number;
    ratingCount: bigint;
    city: string;
    neighborhood: string;
    name: string;
    longitude: number;
    rating: number;
    capacity: bigint;
}
export interface UserProfile {
    city: string;
    neighborhood: string;
    name: string;
    entityType: EntityType;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum DonationStatus {
    pending = "pending",
    pickedUp = "pickedUp",
    rejected = "rejected",
    confirmed = "confirmed",
    accepted = "accepted"
}
export enum EntityType {
    ngo = "ngo",
    admin = "admin",
    hotel = "hotel",
    volunteer = "volunteer"
}
export enum StorageCondition {
    roomTemperature = "roomTemperature",
    refrigerated = "refrigerated",
    hotStorage = "hotStorage"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelClaim(donationId: bigint, volunteerId: bigint): Promise<void>;
    claimDonation(donationId: bigint, volunteerId: bigint): Promise<void>;
    createFoodDonation(donorName: string, foodType: string, quantity: number, unit: string, cookTime: Time, storageCondition: StorageCondition, city: string, neighborhood: string, latitude: number, longitude: number): Promise<bigint>;
    getAllDonations(): Promise<Array<FoodDonation>>;
    getAllNgosSortedByRating(): Promise<Array<NGO>>;
    getAllVolunteersSortedByName(): Promise<Array<Volunteer>>;
    getAvailableDonationsForVolunteers(): Promise<Array<FoodDonation>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFoodDonation(id: bigint): Promise<FoodDonation | null>;
    getImpactCounters(): Promise<ImpactCounters>;
    getMyNgoRating(ngoId: bigint): Promise<number | null>;
    getNgoRatingSummary(ngoId: bigint): Promise<[number, bigint]>;
    getNgosByCity(city: string): Promise<Array<NGO>>;
    getPendingDonationsSortedByTimestamp(): Promise<Array<FoodDonation>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserProfilesByEntityType(entityType: EntityType): Promise<Array<UserProfile>>;
    getVolunteersByCity(city: string): Promise<Array<Volunteer>>;
    isAdminCaller(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    rateNgo(ngoId: bigint, ratingValue: number): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateFoodDonationStatus(id: bigint, newStatus: DonationStatus): Promise<void>;
    updateImpactCounters(mealsSaved: bigint, peopleFed: bigint, co2: number, city: string, cityCount: bigint): Promise<void>;
}
import type { DonationStatus as _DonationStatus, EntityType as _EntityType, FoodDonation as _FoodDonation, StorageCondition as _StorageCondition, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelClaim(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelClaim(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelClaim(arg0, arg1);
            return result;
        }
    }
    async claimDonation(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.claimDonation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimDonation(arg0, arg1);
            return result;
        }
    }
    async createFoodDonation(arg0: string, arg1: string, arg2: number, arg3: string, arg4: Time, arg5: StorageCondition, arg6: string, arg7: string, arg8: number, arg9: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createFoodDonation(arg0, arg1, arg2, arg3, arg4, to_candid_StorageCondition_n10(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFoodDonation(arg0, arg1, arg2, arg3, arg4, to_candid_StorageCondition_n10(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9);
            return result;
        }
    }
    async getAllDonations(): Promise<Array<FoodDonation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDonations();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDonations();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNgosSortedByRating(): Promise<Array<NGO>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNgosSortedByRating();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNgosSortedByRating();
            return result;
        }
    }
    async getAllVolunteersSortedByName(): Promise<Array<Volunteer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVolunteersSortedByName();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVolunteersSortedByName();
            return result;
        }
    }
    async getAvailableDonationsForVolunteers(): Promise<Array<FoodDonation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableDonationsForVolunteers();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableDonationsForVolunteers();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFoodDonation(arg0: bigint): Promise<FoodDonation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFoodDonation(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFoodDonation(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getImpactCounters(): Promise<ImpactCounters> {
        if (this.processError) {
            try {
                const result = await this.actor.getImpactCounters();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getImpactCounters();
            return result;
        }
    }
    async getMyNgoRating(arg0: bigint): Promise<number | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyNgoRating(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyNgoRating(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNgoRatingSummary(arg0: bigint): Promise<[number, bigint]> {
        if (this.processError) {
            try {
                const result = await this.actor.getNgoRatingSummary(arg0);
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNgoRatingSummary(arg0);
            return [
                result[0],
                result[1]
            ];
        }
    }
    async getNgosByCity(arg0: string): Promise<Array<NGO>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNgosByCity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNgosByCity(arg0);
            return result;
        }
    }
    async getPendingDonationsSortedByTimestamp(): Promise<Array<FoodDonation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingDonationsSortedByTimestamp();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingDonationsSortedByTimestamp();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfilesByEntityType(arg0: EntityType): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfilesByEntityType(to_candid_EntityType_n28(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfilesByEntityType(to_candid_EntityType_n28(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVolunteersByCity(arg0: string): Promise<Array<Volunteer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVolunteersByCity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVolunteersByCity(arg0);
            return result;
        }
    }
    async isAdminCaller(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdminCaller();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdminCaller();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async rateNgo(arg0: bigint, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rateNgo(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rateNgo(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n31(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n31(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateFoodDonationStatus(arg0: bigint, arg1: DonationStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFoodDonationStatus(arg0, to_candid_DonationStatus_n33(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFoodDonationStatus(arg0, to_candid_DonationStatus_n33(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateImpactCounters(arg0: bigint, arg1: bigint, arg2: number, arg3: string, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateImpactCounters(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateImpactCounters(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
}
function from_candid_DonationStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DonationStatus): DonationStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_EntityType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EntityType): EntityType {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_FoodDonation_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FoodDonation): FoodDonation {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_StorageCondition_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StorageCondition): StorageCondition {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FoodDonation]): FoodDonation | null {
    return value.length === 0 ? null : from_candid_FoodDonation_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _DonationStatus;
    latitude: number;
    city: string;
    neighborhood: string;
    donorName: string;
    unit: string;
    cookTime: _Time;
    claimedBy: [] | [bigint];
    longitude: number;
    timestamp: _Time;
    quantity: number;
    storageCondition: _StorageCondition;
    foodType: string;
}): {
    id: bigint;
    status: DonationStatus;
    latitude: number;
    city: string;
    neighborhood: string;
    donorName: string;
    unit: string;
    cookTime: Time;
    claimedBy?: bigint;
    longitude: number;
    timestamp: Time;
    quantity: number;
    storageCondition: StorageCondition;
    foodType: string;
} {
    return {
        id: value.id,
        status: from_candid_DonationStatus_n15(_uploadFile, _downloadFile, value.status),
        latitude: value.latitude,
        city: value.city,
        neighborhood: value.neighborhood,
        donorName: value.donorName,
        unit: value.unit,
        cookTime: value.cookTime,
        claimedBy: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.claimedBy)),
        longitude: value.longitude,
        timestamp: value.timestamp,
        quantity: value.quantity,
        storageCondition: from_candid_StorageCondition_n17(_uploadFile, _downloadFile, value.storageCondition),
        foodType: value.foodType
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    city: string;
    neighborhood: string;
    name: string;
    entityType: _EntityType;
}): {
    city: string;
    neighborhood: string;
    name: string;
    entityType: EntityType;
} {
    return {
        city: value.city,
        neighborhood: value.neighborhood,
        name: value.name,
        entityType: from_candid_EntityType_n22(_uploadFile, _downloadFile, value.entityType)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    pickedUp: null;
} | {
    rejected: null;
} | {
    confirmed: null;
} | {
    accepted: null;
}): DonationStatus {
    return "pending" in value ? DonationStatus.pending : "pickedUp" in value ? DonationStatus.pickedUp : "rejected" in value ? DonationStatus.rejected : "confirmed" in value ? DonationStatus.confirmed : "accepted" in value ? DonationStatus.accepted : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    roomTemperature: null;
} | {
    refrigerated: null;
} | {
    hotStorage: null;
}): StorageCondition {
    return "roomTemperature" in value ? StorageCondition.roomTemperature : "refrigerated" in value ? StorageCondition.refrigerated : "hotStorage" in value ? StorageCondition.hotStorage : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ngo: null;
} | {
    admin: null;
} | {
    hotel: null;
} | {
    volunteer: null;
}): EntityType {
    return "ngo" in value ? EntityType.ngo : "admin" in value ? EntityType.admin : "hotel" in value ? EntityType.hotel : "volunteer" in value ? EntityType.volunteer : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FoodDonation>): Array<FoodDonation> {
    return value.map((x)=>from_candid_FoodDonation_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n20(_uploadFile, _downloadFile, x));
}
function to_candid_DonationStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DonationStatus): _DonationStatus {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid_EntityType_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EntityType): _EntityType {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_StorageCondition_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StorageCondition): _StorageCondition {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    city: string;
    neighborhood: string;
    name: string;
    entityType: EntityType;
}): {
    city: string;
    neighborhood: string;
    name: string;
    entityType: _EntityType;
} {
    return {
        city: value.city,
        neighborhood: value.neighborhood,
        name: value.name,
        entityType: to_candid_EntityType_n28(_uploadFile, _downloadFile, value.entityType)
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StorageCondition): {
    roomTemperature: null;
} | {
    refrigerated: null;
} | {
    hotStorage: null;
} {
    return value == StorageCondition.roomTemperature ? {
        roomTemperature: null
    } : value == StorageCondition.refrigerated ? {
        refrigerated: null
    } : value == StorageCondition.hotStorage ? {
        hotStorage: null
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EntityType): {
    ngo: null;
} | {
    admin: null;
} | {
    hotel: null;
} | {
    volunteer: null;
} {
    return value == EntityType.ngo ? {
        ngo: null
    } : value == EntityType.admin ? {
        admin: null
    } : value == EntityType.hotel ? {
        hotel: null
    } : value == EntityType.volunteer ? {
        volunteer: null
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DonationStatus): {
    pending: null;
} | {
    pickedUp: null;
} | {
    rejected: null;
} | {
    confirmed: null;
} | {
    accepted: null;
} {
    return value == DonationStatus.pending ? {
        pending: null
    } : value == DonationStatus.pickedUp ? {
        pickedUp: null
    } : value == DonationStatus.rejected ? {
        rejected: null
    } : value == DonationStatus.confirmed ? {
        confirmed: null
    } : value == DonationStatus.accepted ? {
        accepted: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
